import React, { useState, useEffect } from "react";
import { useDispatch, useSelector } from "react-redux";
import { FaHistory, FaSearch } from "react-icons/fa";
import { TiExportOutline } from "react-icons/ti";
import { useNavigate } from "react-router-dom";
import { IoIosArrowForward } from "react-icons/io";
import * as XLSX from "xlsx";          // ✅ Excel export
import { saveAs } from "file-saver";   // ✅ File download
import {
  fetchAssignedByMeRequest,
  fetchIncidentHistoryRequest,
} from "../../../redux/incident/incidentSlice";
import { fetchAllUsersRequest } from "../../../redux/sltusers/sltusersSlice";
import AffectedUserDetail from "../../../components/AffectedUserDetail/AffectedUserDetail";
import IncidentHistory from "../../../components/IncidentHistory/IncidentHistory";
import "./AdminReportedMyIncidents.css";

const AdminReportedMyIncidents = () => {
  const navigate = useNavigate();
  const dispatch = useDispatch();

  const { assignedByMe, loading, error, incidentHistory } = useSelector(
    (state) => state.incident
  );
  const { user } = useSelector((state) => state.auth);
  const { allUsers } = useSelector((state) => state.sltusers);

  const [searchTerm, setSearchTerm] = useState("");
  const [statusFilter, setStatusFilter] = useState("");
  const [categoryFilter, setCategoryFilter] = useState("");
  const [currentPage, setCurrentPage] = useState(1);
  const [rowsPerPage, setRowsPerPage] = useState(10);
  const [selectedIncident, setSelectedIncident] = useState(null);
  const [isPopupVisible, setIsPopupVisible] = useState(false);

  // ✅ Fetch incidents
  useEffect(() => {
    if (user && user.role === "admin" && user.serviceNumber) {
      dispatch(fetchAssignedByMeRequest({ serviceNum: user.serviceNumber }));
    }
    dispatch(fetchAllUsersRequest());
  }, [dispatch, user]);

  // ✅ Table data
  const tableData = (assignedByMe || []).map((item) => ({
    "Ref No": item.incident_number,
    "Category": item.category,
    "Status": item.status,
    "Priority": item.priority,
    "Informant": item.informant,
  }));

  // ✅ Filter
  const filteredData = tableData.filter((item) => {
    const matchesSearch = Object.values(item).some((val) =>
      String(val).toLowerCase().includes(searchTerm.toLowerCase())
    );
    const matchesStatus = statusFilter ? item.Status === statusFilter : true;
    const matchesCategory = categoryFilter
      ? item.Category === categoryFilter
      : true;
    return matchesSearch && matchesStatus && matchesCategory;
  });

  const totalPages = Math.ceil(filteredData.length / rowsPerPage);
  const indexOfLast = currentPage * rowsPerPage;
  const indexOfFirst = indexOfLast - rowsPerPage;
  const currentRows = filteredData.slice(indexOfFirst, indexOfLast);

  const handleRowClick = (refNo) => {
    const incident = assignedByMe.find(
      (item) => item.incident_number === refNo
    );
    if (incident) {
      setSelectedIncident(incident);
      setIsPopupVisible(true);
      dispatch(fetchIncidentHistoryRequest({ incident_number: refNo }));
    }
  };

  // ✅ Excel Export Function with headers and auto-width
const exportToExcel = () => {
  if (filteredData.length === 0) {
    alert("No data to export!");
    return;
  }

  // Start with the worksheet from data
  const ws = XLSX.utils.json_to_sheet(filteredData, { origin: 5 }); // Start table at row 6

  // Add header info above table
  const headerRows = [
    ["My Reported Incidents Report"], // Title
    [`Generated By: ${user?.userName || ""}`],
    [`Date: ${new Date().toLocaleString()}`],
    [`Total Incidents: ${tableData.length}`],
    [`Filtered Incidents: ${filteredData.length}`],
    [] // empty row before table
  ];
  XLSX.utils.sheet_add_aoa(ws, headerRows, { origin: 0 });

  // Bold table headers (row 6)
  const tableHeaderRowIndex = headerRows.length; // 6
  const range = XLSX.utils.decode_range(ws["!ref"]);
  for (let C = range.s.c; C <= range.e.c; ++C) {
    const cellAddress = XLSX.utils.encode_cell({ r: tableHeaderRowIndex, c: C });
    if (!ws[cellAddress]) continue;
    ws[cellAddress].s = { font: { bold: true } };
  }

  // Auto column width
  const colWidths = Object.keys(filteredData[0]).map((key) => ({
    wch: Math.max(
      key.length,
      ...filteredData.map((row) => (row[key] ? row[key].toString().length : 0))
    ) + 2
  }));
  ws["!cols"] = colWidths;

  const wb = XLSX.utils.book_new();
  XLSX.utils.book_append_sheet(wb, ws, "Reported Incidents");

  const excelBuffer = XLSX.write(wb, { bookType: "xlsx", type: "array" });
  const blob = new Blob([excelBuffer], { type: "application/octet-stream" });
  saveAs(blob, `My_Reported_Incidents_${new Date().toISOString().slice(0, 10)}.xlsx`);
};


  const renderTableRows = () =>
    currentRows.map((row, idx) => (
      <tr key={idx}>
        <td className="AdminReportedMyIncidents-refno">
          <a
            href="#"
            onClick={(e) => {
              e.preventDefault();
              handleRowClick(row["Ref No"]);
            }}
            style={{ color: "#222", textDecoration: "none", cursor: "pointer" }}
          >
            {row["Ref No"]}
          </a>
        </td>
        <td>{row["Category"]}</td>
        <td className="AdminReportedMyIncidents-status-text">{row["Status"]}</td>
        <td>{row["Priority"]}</td>
      </tr>
    ));

  const renderPaginationButtons = () => {
    const maxButtons = 7;
    const buttons = [];

    if (totalPages <= maxButtons) {
      return Array.from({ length: totalPages }, (_, i) => (
        <button
          key={i + 1}
          onClick={() => setCurrentPage(i + 1)}
          className={currentPage === i + 1 ? "active" : ""}
        >
          {i + 1}
        </button>
      ));
    }

    buttons.push(
      <button key={1} onClick={() => setCurrentPage(1)} className={currentPage === 1 ? "active" : ""}>1</button>,
      <button key={2} onClick={() => setCurrentPage(2)} className={currentPage === 2 ? "active" : ""}>2</button>
    );

    if (currentPage > 3) buttons.push(<span key="ellipsis1">...</span>);
    if (currentPage > 3 && currentPage < totalPages - 2)
      buttons.push(
        <button
          key={currentPage}
          onClick={() => setCurrentPage(currentPage)}
          className="active"
        >
          {currentPage}
        </button>
      );
    if (currentPage < totalPages - 2) buttons.push(<span key="ellipsis2">...</span>);
    buttons.push(
      <button key={totalPages - 1} onClick={() => setCurrentPage(totalPages - 1)} className={currentPage === totalPages - 1 ? "active" : ""}>{totalPages - 1}</button>,
      <button key={totalPages} onClick={() => setCurrentPage(totalPages)} className={currentPage === totalPages ? "active" : ""}>{totalPages}</button>
    );

    return buttons;
  };

  const renderPopup = () => {
    if (!isPopupVisible || !selectedIncident) return null;

    const formData = {
      serviceNo: user.serviceNumber,
      tpNumber: user.tp_number || user.tpNumber || user.contactNumber || "",
      name: user.userName,
      designation: user.designation || user.role || "",
      email: user.email,
    };

    const incidentDetails = {
      refNo: selectedIncident.incident_number,
      category: selectedIncident.category,
      location: selectedIncident.location,
      priority: selectedIncident.priority,
      status: selectedIncident.status,
    };

    return (
      <div className="popup-overlay">
        <div className="popup-content">
          <button
            className="popup-close"
            onClick={() => setIsPopupVisible(false)}
          >
            X
          </button>
          <br /><br />
          <div className="AdminMyReportedUpdate-content2">
            <AffectedUserDetail formData={formData} />
            <br />
            <IncidentHistory
              refNo={incidentDetails.refNo}
              category={incidentDetails.category}
              location={incidentDetails.location}
              priority={incidentDetails.priority}
              status={incidentDetails.status}
              historyData={incidentHistory}
              users={allUsers}
            />
          </div>
        </div>
      </div>
    );
  };

  if (!user) return <div>Loading user data...</div>;
  if (!user.serviceNumber) return <div>User data missing serviceNumber.</div>;
  if (user.role !== "admin") return <div>Unauthorized</div>;

  return (
    <div className="AdminReportedMyIncidents-main-content">
      {renderPopup()}
      <div className="AdminReportedMyIncidents-tickets-creator">
        <span className="AdminReportedMyIncidents-svr-desk">Incidents</span>
        <IoIosArrowForward />
        <span className="AdminReportedMyIncidents-created-ticket">Reported My</span>
      </div>

      <div className="AdminReportedMyIncidents-content2">
        <div className="AdminReportedMyIncidents-TitleBar">
          <div className="AdminReportedMyIncidents-TitleBar-NameAndIcon">
            <FaHistory size={20} /> My Incidents - {user.userName}
          </div>
          <div className="AdminReportedMyIncidents-TitleBar-buttons">
            <button
              className="AdminReportedMyIncidents-TitleBar-buttons-ExportData"
              onClick={exportToExcel}
            >
              <TiExportOutline /> Export Data
            </button>
          </div>
        </div>

        {/* Search & Filters */}
        <div className="AdminReportedMyIncidents-showSearchBar container-fluid p-0">
          <div className="row m-0 w-100">
            <div className="col-md-7 col-lg-8 p-0">
              <div className="AdminReportedMyIncidents-showSearchBar-Show d-flex flex-wrap align-items-center">
                <div className="d-flex align-items-center me-3 mb-2 mb-sm-0">
                  Entries:
                  <select
                    onChange={(e) => setRowsPerPage(Number(e.target.value))}
                    value={rowsPerPage}
                    className="AdminReportedMyIncidents-showSearchBar-Show-select ms-2"
                  >
                    {[10, 20, 50, 100].map((size) => (
                      <option key={size} value={size}>{size} entries</option>
                    ))}
                  </select>
                </div>
                <div className="d-flex align-items-center me-3 mb-2 mb-sm-0">
                  Status:
                  <select
                    onChange={(e) => setStatusFilter(e.target.value)}
                    value={statusFilter}
                    className="AdminReportedMyIncidents-showSearchBar-Show-select ms-2"
                  >
                    <option value="">All Status</option>
                    <option value="Open">Open</option>
                    <option value="Hold">Hold</option>
                    <option value="In Progress">In Progress</option>
                    <option value="Closed">Closed</option>
                  </select>
                </div>
              </div>
            </div>
            <div className="col-md-5 col-lg-4 p-0 d-flex justify-content-md-end justify-content-start mt-2 mt-md-0">
              <div className="AdminReportedMyIncidents-showSearchBar-SearchBar">
                <FaSearch />
                <input
                  type="text"
                  placeholder="Search..."
                  value={searchTerm}
                  onChange={(e) => setSearchTerm(e.target.value)}
                  className="AdminReportedMyIncidents-showSearchBar-SearchBar-input"
                />
              </div>
            </div>
          </div>
        </div>

        {/* Table */}
        <div className="AdminReportedMyIncidents-table">
          <table className="AdminReportedMyIncidents-table-table">
            <thead>
              <tr>
                <th>Ref No</th>
                <th>Category</th>
                <th>Status</th>
                <th>Priority</th>
              </tr>
            </thead>
            <tbody>
              {filteredData.length === 0 ? (
                <tr>
                  <td colSpan="4" className="AdminReportedMyIncidents-no-data">
                    No incidents found matching the criteria.
                  </td>
                </tr>
              ) : renderTableRows()}
            </tbody>
          </table>
        </div>

        {/* Pagination */}
        <div className="AdminReportedMyIncidents-content3">
          <span className="AdminReportedMyIncidents-content3-team-entry-info">
            Showing {indexOfFirst + 1} to {Math.min(indexOfLast, filteredData.length)} of {filteredData.length} entries
          </span>
          <div className="AdminReportedMyIncidents-content3-team-pagination-buttons">
            <button onClick={() => setCurrentPage(prev => Math.max(prev - 1, 1))} disabled={currentPage === 1}>Previous</button>
            {renderPaginationButtons()}
            <button onClick={() => setCurrentPage(prev => Math.min(prev + 1, totalPages))} disabled={currentPage === totalPages}>Next</button>
          </div>
        </div>
      </div>
    </div>
  );
};

export default AdminReportedMyIncidents;
